### ISSUE TITLE
ToDo list for next update

### ISSUE THREAD

**Issue by TCLamnidis** [Schiffels-Popgen/MICROSCOPE-processing-pipeline#13]
nf-core/eager prep:
- [ ] Swap to using pandora2eager instead of its predecessor. This mostly updates the pickup of strandedness, udg treatment, and colour chemistry for newer protocols/sequencers.

Poseidon packages:
- [ ] collecting ssDNA and dsDNA genotypes in each package (there should be no clashing sample IDs anymore) (#8)
  - [ ] Collecting the genotypes for poseidon package creation
  - [ ] Janno fill-in for both versions

PDF Reports:
- [ ] BUG: Currently, only info for TF and SG are kept in the run table. Keep RP/RM as well for future reports.
- [ ] Update report to pull info from janno files instead of pandora. This is a leftover from before the jannos were automatically filled in, and no longer necessary.
- [ ] Remove Arch IDs from Read table (#12)
- [ ] Add lexicon to reports (#11)

Phenotypic SNPs: 
- #10 : Some fixes were already done, but proper curation of a SNP list was never my intention, so I will not be extending the list for now. 

Processing:
 - [ ] Have each eager run start from a stable, unique directory, to allow parallelisation and more reliable resuming (#6)

**Comment by TCLamnidis** [comment]
Using pandora2eager for TSV preparation actually revealed a small bug. The previous approach required some manual tweaks for certain samples, and hence some Sample_IDs did not get the appropriate suffix. This is not an issue until genotypes are collected together, but might require some slight reprocessing to fix properly

**Comment by stschiff** [comment]
OK, but just to clarify: You did not fix the _ss suffix where they were missing now? I think that's OK, just want to be sure.

**Comment by TCLamnidis** [comment]
@stschiff that is correct. As soon as such batches get new data, they would be updated anyway, so if they lack it now it is because there have been no updates to those batches in a while (~1.5y-2y).

**Comment by TCLamnidis** [comment]
I had not, until now. 
Both of the aforementioned batches needed reprocessing to fix ssDNA/PE adapter leftovers, so I took the opportunity to also fix the suffixes for them.
